EZPI-536 Update template files
ezloteam/Ezlo_Pi pull request #204
Opened 2024-11-22 07:53 UTC by ezlo-gary

## Description:

Update code template files for standardised format. This is the precursor to applying templates to all EzloPi files which have not already have headers etc (ie not files from 3rd parties such as Bosch).

https://jira.mios.com/browse/EZPI-536

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] The code change is tested and works with EzloPi core
  - [x] I accept the [CLA](https://github.com/ezloteam/Ezlo_Pi/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla).

2024-12-02 08:09 UTC, lomasSE89 submitted a review, later dismissed

2024-12-02 10:26 UTC, lomasSE89 requested changes
Please make PR agains development branch only.

2024-12-02 10:28 UTC, ezlo-gary commented
> Please make PR agains development branch only.

Understood 👍

2024-12-03 11:31 UTC, lomasSE89 approved these changes

2024-12-03 11:37 UTC, merged